# Generated by Django 3.2.16 on 2022-12-30 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_ranking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='trainings',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
