# Generated by Django 3.2.16 on 2023-01-04 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_plan_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
