# Generated by Django 3.2.16 on 2023-08-23 04:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_emergency_contact_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('membership_type', models.CharField(choices=[('MENSUAL', 'Mensualidad'), ('QUARTER', 'Trimestre'), ('SEMESTER', 'Semestre')], default='MENSUAL', max_length=10)),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
                ('init_date', models.DateField(help_text='Inicio de membresía', verbose_name='Fecha de inicio')),
                ('expiration_date', models.DateField(blank=True, help_text='Fecha de expiración membresía', null=True, verbose_name='Expiration force date')),
                ('days_duration', models.IntegerField(default=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membresía de usuario',
                'verbose_name_plural': 'Membresías de usuarios',
            },
        ),
        migrations.AddConstraint(
            model_name='usermembership',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user',), name='unique_membership'),
        ),
    ]
