# Generated by Django 3.2.16 on 2023-08-24 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20230822_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermembership',
            name='expiration_date',
            field=models.DateField(blank=True, help_text='Fecha de expiración membresía', null=True, verbose_name='Fecha fin de membresía'),
        ),
        migrations.AlterField(
            model_name='usermembership',
            name='init_date',
            field=models.DateField(help_text='Inicio de membresía', verbose_name='Fecha de inicio membresía'),
        ),
    ]
