# Generated by Django 4.1.4 on 2025-01-17 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_auto_20230823_2304"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserStrike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last modified.",
                        verbose_name="modified at",
                    ),
                ),
                ("weeks", models.PositiveIntegerField(default=0)),
                (
                    "is_current",
                    models.BooleanField(default=False, verbose_name="Current"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="strikes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Strike",
                "verbose_name_plural": "Strikes",
            },
        ),
        migrations.CreateModel(
            name="UserStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last modified.",
                        verbose_name="modified at",
                    ),
                ),
                ("week", models.PositiveIntegerField(default=0)),
                ("calories", models.PositiveIntegerField(default=0)),
                ("hours", models.PositiveIntegerField(default=0)),
                ("trainings", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Stats",
                "verbose_name_plural": "Stats",
            },
        ),
        migrations.AddConstraint(
            model_name="userstrike",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("user",),
                name="unique_strike",
            ),
        ),
        migrations.AddConstraint(
            model_name="userstats",
            constraint=models.UniqueConstraint(
                fields=("user", "week"), name="unique_stats"
            ),
        ),
    ]
