# Generated by Django 4.1.4 on 2025-01-18 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_userstrike_userstats_userstrike_unique_strike_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="users/photos/",
                verbose_name="profile picture",
            ),
        ),
    ]
