# Generated by Django 4.1.4 on 2025-01-18 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_user_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="userstats",
            name="year",
            field=models.PositiveIntegerField(default=2025),
        ),
    ]
