# Generated by Django 4.1.4 on 2025-01-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_userstats_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="userstrike",
            name="last_week",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
