# Generated by Django 4.1.4 on 2025-01-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_userstrike_last_week"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userstats",
            name="week",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="userstrike",
            name="is_current",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Current"
            ),
        ),
        migrations.AlterField(
            model_name="userstrike",
            name="weeks",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
