# Generated by Django 4.2 on 2025-01-20 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_neuralplan"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermembership",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="memberships",
                to="users.neuralplan",
            ),
        ),
    ]
