# Generated by Django 4.2 on 2025-01-20 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_userpaymentreference"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpaymentreference",
            name="data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
