# Generated by Django 4.2 on 2025-01-20 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_userpaymentreference_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usermembership",
            name="days_duration",
        ),
    ]
