# Generated by Django 4.2 on 2025-12-24 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0021_device"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="users/photos/",
                verbose_name="profile picture",
            ),
        ),
    ]
