# Generated by Django 4.2 on 2025-12-24 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0022_profile_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profiles",
                to="users.plan",
            ),
        ),
    ]
