# Generated by Django 4.2 on 2025-12-24 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0024_profile_height_userweight"),
    ]

    operations = [
        migrations.CreateModel(
            name="PushNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last modified.",
                        verbose_name="modified at",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField()),
                (
                    "data",
                    models.JSONField(
                        blank=True, help_text="Extra payload data", null=True
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("training_reminder", "Recordatorio de entrenamiento"),
                            ("training_cancelled", "Entrenamiento cancelado"),
                            ("membership_expiring", "Membresía por vencer"),
                            ("membership_expired", "Membresía vencida"),
                            ("achievement", "Logro desbloqueado"),
                            ("promotion", "Promoción"),
                        ],
                        default="general",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("sent", "Enviada"),
                            ("delivered", "Entregada"),
                            ("failed", "Fallida"),
                            ("read", "Leída"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("scheduled_for", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificación",
                "verbose_name_plural": "Notificaciones",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="PushNotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last modified.",
                        verbose_name="modified at",
                    ),
                ),
                ("expo_push_token", models.CharField(max_length=500)),
                ("request_payload", models.JSONField(help_text="Request sent to Expo")),
                (
                    "response_payload",
                    models.JSONField(
                        blank=True, help_text="Response from Expo", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Éxito"), ("error", "Error")],
                        default="success",
                        max_length=20,
                    ),
                ),
                (
                    "expo_receipt_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notification_logs",
                        to="users.device",
                    ),
                ),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="users.pushnotification",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de notificación",
                "verbose_name_plural": "Logs de notificaciones",
            },
        ),
    ]
