# Generated by Django 4.2 on 2025-12-25 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0025_pushnotification_pushnotificationlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pushnotification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("training_reminder", "Recordatorio de entrenamiento"),
                    ("training_cancelled", "Entrenamiento cancelado"),
                    ("membership_expiring", "Membresía por vencer"),
                    ("membership_expired", "Membresía vencida"),
                    ("achievement", "Logro desbloqueado"),
                    ("promotion", "Promoción"),
                    ("community", "Comunidad"),
                ],
                default="general",
                max_length=30,
            ),
        ),
    ]
