# Generated by Django 4.2 on 2026-01-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0026_alter_pushnotification_notification_type"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="userstats",
            name="unique_stats",
        ),
        migrations.AlterField(
            model_name="userstats",
            name="year",
            field=models.PositiveIntegerField(default=2026),
        ),
        migrations.AddConstraint(
            model_name="userstats",
            constraint=models.UniqueConstraint(
                fields=("user", "year", "week"), name="unique_stats_per_year"
            ),
        ),
    ]
