# Generated by Django 3.0.11 on 2020-11-22 23:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertraining',
            name='user',
            field=models.ForeignKey(limit_choices_to={'is_verified': True}, on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to=settings.AUTH_USER_MODEL),
        ),
    ]
