# Generated by Django 3.0.11 on 2020-11-23 06:15

from django.db import migrations
from neural.training.models import Space

def create_spaces(apps, schema_editor):
    for i in range(1, 13):
        Space.objects.get_or_create(
            name=f'Base {i}'
        )

class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_auto_20201123_0110'),
    ]

    operations = [
        migrations.RunPython(create_spaces)
    ]
