# Generated by Django 3.0.11 on 2020-11-25 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_usertraining_space'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='training_type',
            field=models.CharField(choices=[('NEURAL_CIRCUIT', 'Neural Circuit'), ('POWER_HOUR', 'Power Hour'), ('BALANCE', 'Balance'), ('WORKOUT', 'Workout Energy')], default='NEURAL_CIRCUIT', max_length=50),
        ),
    ]
