# Generated by Django 3.0.11 on 2021-01-20 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_auto_20201125_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertraining',
            name='space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_trainings', to='training.Space'),
        ),
        migrations.AlterField(
            model_name='usertraining',
            name='status',
            field=models.CharField(choices=[('CANCELLED', 'Cancelada'), ('CONFIRMED', 'Confirmada'), ('DONE', 'Terminada')], default='CONFIRMED', max_length=50),
        ),
    ]
