# Generated by Django 3.1.7 on 2021-03-13 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0008_usertemperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='training_type',
            field=models.CharField(choices=[('NEURAL_CIRCUIT', 'Neural Circuit'), ('POWER_HOUR', 'Power Hour'), ('BALANCE', 'Balance'), ('WORKOUT', 'Workout Energy'), ('SPECIAL', 'Special class')], default='NEURAL_CIRCUIT', max_length=50),
        ),
    ]
