# Generated by Django 3.2 on 2021-04-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0009_auto_20210313_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='training_type',
            field=models.CharField(choices=[('NEURAL_CIRCUIT', 'Neural Circuit'), ('POWER_HOUR', 'Power Hour'), ('BALANCE', 'Balance'), ('WORKOUT', 'Workout Energy'), ('VIRTUAL', 'Virtual'), ('SPECIAL', 'Special class')], default='NEURAL_CIRCUIT', max_length=50),
        ),
    ]
