# Generated by Django 3.2.7 on 2021-09-08 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0012_alter_slot_training_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserTemperature',
        ),
    ]
