# Generated by Django 3.2.10 on 2022-05-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0017_alter_slot_training_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='training_type',
            field=models.CharField(choices=[('FUNCIONAL_TRAINING', 'Funcional Training'), ('GAP_MMSS', 'GAP/MMSS'), ('CARDIO_STEP', 'Cardio Step'), ('SENIOR', 'Senior'), ('RTG', 'RTG'), ('PILATES', 'Pilates'), ('FIT_BOXING', 'Fit Boxing'), ('BALANCE', 'Balance'), ('SUPERSTAR', 'Super Star'), ('CARDIOHIT', 'Cardio Hit'), ('A_FUEGO', 'A Fuego'), ('RUMBA', 'Rumba')], default='FUNCIONAL_TRAINING', max_length=50),
        ),
    ]
