# Generated by Django 3.2.10 on 2022-07-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0018_alter_slot_training_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagePopUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('image_name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='pop_ups')),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Image pop up',
                'verbose_name_plural': 'Images pop ups',
            },
        ),
    ]
