# Generated by Django 3.2.16 on 2023-01-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0020_alter_slot_training_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='training_type',
            field=models.CharField(choices=[('FUNCIONAL_TRAINING', 'Funcional Training'), ('GAP_MMSS', 'GAP'), ('CARDIO_STEP', 'Aeroibic Step'), ('SENIOR', 'Senior'), ('RTG', 'RTG'), ('PILATES', 'Pilates'), ('FIT_BOXING', 'Funcional box'), ('BALANCE', 'Balance'), ('SUPERSTAR', 'Super Star'), ('CARDIOHIT', 'Cardio Hit'), ('A_FUEGO', 'Solo pernil'), ('RUMBA', 'Rumba')], default='FUNCIONAL_TRAINING', max_length=50),
        ),
    ]
