# Generated by Django 3.2.16 on 2023-09-11 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0021_alter_slot_training_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('name', models.CharField(max_length=255)),
                ('slug_name', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de entrenamiento',
                'verbose_name_plural': 'Tipos de entrenamientos',
            },
        ),
        migrations.RemoveField(
            model_name='slot',
            name='hour_end',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='hour_init',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='training_type',
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('day', models.CharField(choices=[('MONDAY', 'Lunes'), ('TUESADAY', 'Martes'), ('WEDNESDAY', 'Miércoles'), ('THURSDAY', 'Jueves'), ('FRIDAY', 'Viernes'), ('SATURDAY', 'Sábado'), ('SUNDAY', 'Domingo')], default='MONDAY', max_length=10)),
                ('hour_init', models.TimeField()),
                ('hour_end', models.TimeField()),
                ('training_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='training.trainingtype')),
            ],
            options={
                'verbose_name': 'Calendario de clases',
                'verbose_name_plural': 'Calendario de clases',
            },
        ),
        migrations.AddField(
            model_name='slot',
            name='class_trainging',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='training.classes'),
        ),
    ]
