# Generated by Django 3.2.16 on 2023-09-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0022_auto_20230911_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='day',
            field=models.CharField(choices=[('MONDAY', 'Lunes'), ('TUESDAY', 'Martes'), ('WEDNESDAY', 'Miércoles'), ('THURSDAY', 'Jueves'), ('FRIDAY', 'Viernes'), ('SATURDAY', 'Sábado'), ('SUNDAY', 'Domingo')], default='MONDAY', max_length=10),
        ),
    ]
