# Generated by Django 3.2.16 on 2023-10-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0023_alter_classes_day'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slot',
            options={'ordering': ['-date']},
        ),
        migrations.AddConstraint(
            model_name='classes',
            constraint=models.UniqueConstraint(fields=('day', 'hour_init', 'hour_end'), name='unique_class_combination'),
        ),
    ]
