# Generated by Django 4.1.4 on 2024-10-02 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0024_auto_20231002_1137"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingtype",
            name="is_group",
            field=models.BooleanField(default=True),
        ),
    ]
