# Generated by Django 4.1.4 on 2024-10-02 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0025_trainingtype_is_group"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="classes",
            name="unique_class_combination",
        ),
        migrations.AddConstraint(
            model_name="classes",
            constraint=models.UniqueConstraint(
                fields=("day", "hour_init", "hour_end", "training_type"),
                name="unique_class_combination",
            ),
        ),
    ]
