# Generated by Django 4.1.4 on 2025-01-17 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0026_remove_classes_unique_class_combination_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ImagePopUp",
        ),
    ]
