# Generated by Django 4.2 on 2025-08-16 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0027_delete_imagepopup"),
    ]

    operations = [
        migrations.RenameField(
            model_name="slot",
            old_name="class_trainging",
            new_name="class_training",
        ),
    ]
